name: Terraform AWS Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  tf_code_check:
    name: Terraform Validation and Build 
    runs-on: ubuntu-latest 

    defaults:
      run:
        shell: bash

    steps: 
    - uses: actions/checkout@v3 

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: eu-north-1 

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init

    - name: Terraform Format 
      run: terraform fmt -check

    - name: Terraform Plan 
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false